add new agrusment whether to remove core set from refined set
cyhFlight/dgl-lifesci pull request #1
Opened 2021-01-28 07:16 UTC by zhuhui-in

2021-01-29 01:58 UTC, zhuhui-in commented
Besides, I retrain PotentialNet on modified refined set and test on core set with random splitting method. The performance showed that the model has limited generalization ability.
![refined_core](https://user-images.githubusercontent.com/69226545/106221352-71a04c80-6218-11eb-9883-5cbb76614843.png)

2021-03-11 07:38 UTC, cyhFlight commented on python/dgllife/data/pdbbind.py
> +                with open (extracted_data_path + '/2007/INDEX.2017.core.data','r') as f:
`'/2007/INDEX.2017.core.data'` should be `'/2007/INDEX.2007.core.data'`

2021-03-11 07:39 UTC, cyhFlight commented on python/dgllife/data/pdbbind.py
> +                            pdbs.remove(fields[0])
Fix `fielsd` for `fields`

2021-03-11 07:42 UTC, cyhFlight commented on python/dgllife/data/pdbbind.py
> +                 zero_padding=True, num_processes=None, **kwargs):
Why do we need `**kwargs`?

2021-03-11 07:50 UTC, cyhFlight requested changes
Thanks very much for adding this feature. Fix the typos and I will merge the changes. Appreciate your efforts.

2021-03-14 05:30 UTC, zhuhui-in commented on python/dgllife/data/pdbbind.py
> +                 zero_padding=True, num_processes=None, **kwargs):
not necessarily.

2021-03-14 15:10 UTC, closed without merging